kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: fabric-pvc
  namespace: boppudi  
spec:
  accessModes:
    - ReadWriteMany
  resources: 
    requests:
      storage: 1Gi
  selector:
     matchLabels:
        name: fabricfiles   

